---
apiVersion: v1
kind: ConfigMap
metadata:
  name: timbrook-nginx-conf
data:
  timbrook.dev.conf: |
    server {
      listen 80;
      listen 443 ssl;
      server_name timbrook.dev;
      ssl_certificate /etc/ssl/timbrook.dev/tls.crt;
      ssl_certificate_key /etc/ssl/timbrook.dev/tls.key;
      root /usr/share/nginx/html;
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      volumes:
        - name: site
          configMap:
            name: timbrook-nginx-conf
        - name: keys
          secret:
            secretName: timbrook-dot-dev-tls
      containers:
        - name: web
          image: nginx
          resources:
            limits:
              memory: "128Mi"
              cpu: "100m"
          ports:
            - containerPort: 80
              name: http
            - containerPort: 433
              name: https
          volumeMounts:
            - name: site
              mountPath: /etc/nginx/conf.d/
            - name: keys
              mountPath: /etc/ssl/timbrook.dev/
              readOnly: true
---
kind: Service
apiVersion: v1
metadata:
  name: web
spec:
  selector:
    app: web
  type: LoadBalancer
  ports:
    - name: http
      port: 80
    - name: https
      port: 443
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: timbrook-dot-dev
spec:
  secretName: timbrook-dot-dev-tls
  issuerRef:
    name: le-prod
  commonName: timbrook.dev
  dnsNames:
    - timbrook.dev
